-- workspaces: one per tenant; user_id links to auth.users
create table public.workspaces (
  id bigint generated by default as identity primary key,
  name text not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  disabled boolean not null default false,
  created_at timestamptz not null default now()
);

-- Index for looking up workspaces by owner and filtering active
create index workspaces_user_id_idx on public.workspaces (user_id);
create index workspaces_disabled_idx on public.workspaces (disabled);

-- RLS
alter table public.workspaces enable row level security;

-- Users can only access their own workspaces
create policy "Users can manage own workspaces"
  on public.workspaces
  for all
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- Optional: allow service role to bypass (for admin/backfills)
-- comment out if you rely only on auth.uid()
